/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
export const ResponsesFormatJSONObjectType = {
    JsonObject: "json_object",
};
/** @internal */
export const ResponsesFormatJSONObjectType$inboundSchema = z.enum(ResponsesFormatJSONObjectType);
/** @internal */
export const ResponsesFormatJSONObjectType$outboundSchema = ResponsesFormatJSONObjectType$inboundSchema;
/** @internal */
export const ResponsesFormatJSONObject$inboundSchema = z.object({
    type: ResponsesFormatJSONObjectType$inboundSchema,
});
/** @internal */
export const ResponsesFormatJSONObject$outboundSchema = z.object({
    type: ResponsesFormatJSONObjectType$outboundSchema,
});
export function responsesFormatJSONObjectToJSON(responsesFormatJSONObject) {
    return JSON.stringify(ResponsesFormatJSONObject$outboundSchema.parse(responsesFormatJSONObject));
}
export function responsesFormatJSONObjectFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponsesFormatJSONObject$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponsesFormatJSONObject' from JSON`);
}
//# sourceMappingURL=responsesformatjsonobject.js.map