/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
export const ChatMessageContentItemAudioFormat = {
    Wav: "wav",
    Mp3: "mp3",
    Flac: "flac",
    M4a: "m4a",
    Ogg: "ogg",
    Pcm16: "pcm16",
    Pcm24: "pcm24",
};
/** @internal */
export const ChatMessageContentItemAudioFormat$inboundSchema = openEnums.inboundSchema(ChatMessageContentItemAudioFormat);
/** @internal */
export const ChatMessageContentItemAudioFormat$outboundSchema = openEnums.outboundSchema(ChatMessageContentItemAudioFormat);
/** @internal */
export const ChatMessageContentItemAudioInputAudio$inboundSchema = z.object({
    data: z.string(),
    format: ChatMessageContentItemAudioFormat$inboundSchema,
});
/** @internal */
export const ChatMessageContentItemAudioInputAudio$outboundSchema = z.object({
    data: z.string(),
    format: ChatMessageContentItemAudioFormat$outboundSchema,
});
export function chatMessageContentItemAudioInputAudioToJSON(chatMessageContentItemAudioInputAudio) {
    return JSON.stringify(ChatMessageContentItemAudioInputAudio$outboundSchema.parse(chatMessageContentItemAudioInputAudio));
}
export function chatMessageContentItemAudioInputAudioFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItemAudioInputAudio$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItemAudioInputAudio' from JSON`);
}
/** @internal */
export const ChatMessageContentItemAudio$inboundSchema = z.object({
    type: z.literal("input_audio"),
    input_audio: z.lazy(() => ChatMessageContentItemAudioInputAudio$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "input_audio": "inputAudio",
    });
});
/** @internal */
export const ChatMessageContentItemAudio$outboundSchema = z.object({
    type: z.literal("input_audio"),
    inputAudio: z.lazy(() => ChatMessageContentItemAudioInputAudio$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        inputAudio: "input_audio",
    });
});
export function chatMessageContentItemAudioToJSON(chatMessageContentItemAudio) {
    return JSON.stringify(ChatMessageContentItemAudio$outboundSchema.parse(chatMessageContentItemAudio));
}
export function chatMessageContentItemAudioFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItemAudio$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItemAudio' from JSON`);
}
//# sourceMappingURL=chatmessagecontentitemaudio.js.map