/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const FileCitationType = {
    FileCitation: "file_citation",
};
/** @internal */
export const FileCitationType$inboundSchema = z.enum(FileCitationType);
/** @internal */
export const FileCitationType$outboundSchema = FileCitationType$inboundSchema;
/** @internal */
export const FileCitation$inboundSchema = z
    .object({
    type: FileCitationType$inboundSchema,
    file_id: z.string(),
    filename: z.string(),
    index: z.number(),
}).transform((v) => {
    return remap$(v, {
        "file_id": "fileId",
    });
});
/** @internal */
export const FileCitation$outboundSchema = z.object({
    type: FileCitationType$outboundSchema,
    fileId: z.string(),
    filename: z.string(),
    index: z.number(),
}).transform((v) => {
    return remap$(v, {
        fileId: "file_id",
    });
});
export function fileCitationToJSON(fileCitation) {
    return JSON.stringify(FileCitation$outboundSchema.parse(fileCitation));
}
export function fileCitationFromJSON(jsonString) {
    return safeParse(jsonString, (x) => FileCitation$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'FileCitation' from JSON`);
}
//# sourceMappingURL=filecitation.js.map