/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
function unrecognized(value) {
    globalCount++;
    return value;
}
let globalCount = 0;
let refCount = 0;
export function startCountingUnrecognized() {
    refCount++;
    const start = globalCount;
    return {
        end: () => {
            const count = globalCount - start;
            if (--refCount === 0)
                globalCount = 0;
            return count;
        },
    };
}
export { unrecognized };
//# sourceMappingURL=unrecognized.js.map