/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as openEnums from "../types/enums.js";
export const OpenAIResponsesTruncation = {
    Auto: "auto",
    Disabled: "disabled",
};
/** @internal */
export const OpenAIResponsesTruncation$inboundSchema = openEnums.inboundSchema(OpenAIResponsesTruncation);
//# sourceMappingURL=openairesponsestruncation.js.map