/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
export const GetParametersProvider = {
    Ai21: "AI21",
    AionLabs: "AionLabs",
    Alibaba: "Alibaba",
    AmazonBedrock: "Amazon Bedrock",
    Anthropic: "Anthropic",
    Arcee: "Arcee",
    AtlasCloud: "AtlasCloud",
    Avian: "Avian",
    Azure: "Azure",
    BaseTen: "BaseTen",
    BlackForestLabs: "Black Forest Labs",
    Cerebras: "Cerebras",
    Chutes: "Chutes",
    Cirrascale: "Cirrascale",
    Clarifai: "Clarifai",
    Cloudflare: "Cloudflare",
    Cohere: "Cohere",
    Crusoe: "Crusoe",
    DeepInfra: "DeepInfra",
    DeepSeek: "DeepSeek",
    Featherless: "Featherless",
    Fireworks: "Fireworks",
    Friendli: "Friendli",
    GMICloud: "GMICloud",
    Google: "Google",
    GoogleAIStudio: "Google AI Studio",
    Groq: "Groq",
    Hyperbolic: "Hyperbolic",
    Inception: "Inception",
    InferenceNet: "InferenceNet",
    Infermatic: "Infermatic",
    Inflection: "Inflection",
    Liquid: "Liquid",
    Mancer2: "Mancer 2",
    Minimax: "Minimax",
    ModelRun: "ModelRun",
    Mistral: "Mistral",
    Modular: "Modular",
    MoonshotAI: "Moonshot AI",
    Morph: "Morph",
    NCompass: "NCompass",
    Nebius: "Nebius",
    NextBit: "NextBit",
    Novita: "Novita",
    Nvidia: "Nvidia",
    OpenAI: "OpenAI",
    OpenInference: "OpenInference",
    Parasail: "Parasail",
    Perplexity: "Perplexity",
    Phala: "Phala",
    Relace: "Relace",
    SambaNova: "SambaNova",
    SiliconFlow: "SiliconFlow",
    Stealth: "Stealth",
    Switchpoint: "Switchpoint",
    Targon: "Targon",
    Together: "Together",
    Venice: "Venice",
    WandB: "WandB",
    XAI: "xAI",
    ZAi: "Z.AI",
    FakeProvider: "FakeProvider",
};
export const SupportedParameter = {
    Temperature: "temperature",
    TopP: "top_p",
    TopK: "top_k",
    MinP: "min_p",
    TopA: "top_a",
    FrequencyPenalty: "frequency_penalty",
    PresencePenalty: "presence_penalty",
    RepetitionPenalty: "repetition_penalty",
    MaxTokens: "max_tokens",
    LogitBias: "logit_bias",
    Logprobs: "logprobs",
    TopLogprobs: "top_logprobs",
    Seed: "seed",
    ResponseFormat: "response_format",
    StructuredOutputs: "structured_outputs",
    Stop: "stop",
    Tools: "tools",
    ToolChoice: "tool_choice",
    ParallelToolCalls: "parallel_tool_calls",
    IncludeReasoning: "include_reasoning",
    Reasoning: "reasoning",
    WebSearchOptions: "web_search_options",
    Verbosity: "verbosity",
};
/** @internal */
export const GetParametersSecurity$outboundSchema = z.object({
    bearer: z.string(),
});
export function getParametersSecurityToJSON(getParametersSecurity) {
    return JSON.stringify(GetParametersSecurity$outboundSchema.parse(getParametersSecurity));
}
/** @internal */
export const GetParametersProvider$outboundSchema = openEnums.outboundSchema(GetParametersProvider);
/** @internal */
export const GetParametersRequest$outboundSchema = z.object({
    author: z.string(),
    slug: z.string(),
    provider: GetParametersProvider$outboundSchema.optional(),
});
export function getParametersRequestToJSON(getParametersRequest) {
    return JSON.stringify(GetParametersRequest$outboundSchema.parse(getParametersRequest));
}
/** @internal */
export const SupportedParameter$inboundSchema = openEnums.inboundSchema(SupportedParameter);
/** @internal */
export const GetParametersData$inboundSchema = z.object({
    model: z.string(),
    supported_parameters: z.array(SupportedParameter$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "supported_parameters": "supportedParameters",
    });
});
export function getParametersDataFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetParametersData$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetParametersData' from JSON`);
}
/** @internal */
export const GetParametersResponse$inboundSchema = z.object({
    data: z.lazy(() => GetParametersData$inboundSchema),
});
export function getParametersResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetParametersResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetParametersResponse' from JSON`);
}
//# sourceMappingURL=getparameters.js.map