/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
export const ResponsesFormatTextType = {
    Text: "text",
};
/** @internal */
export const ResponsesFormatTextType$inboundSchema = z.enum(ResponsesFormatTextType);
/** @internal */
export const ResponsesFormatTextType$outboundSchema = ResponsesFormatTextType$inboundSchema;
/** @internal */
export const ResponsesFormatText$inboundSchema = z.object({
    type: ResponsesFormatTextType$inboundSchema,
});
/** @internal */
export const ResponsesFormatText$outboundSchema = z.object({
    type: ResponsesFormatTextType$outboundSchema,
});
export function responsesFormatTextToJSON(responsesFormatText) {
    return JSON.stringify(ResponsesFormatText$outboundSchema.parse(responsesFormatText));
}
export function responsesFormatTextFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponsesFormatText$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponsesFormatText' from JSON`);
}
//# sourceMappingURL=responsesformattext.js.map