/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { ChatStreamOptions$outboundSchema, } from "./chatstreamoptions.js";
import { Message$outboundSchema, } from "./message.js";
import { ReasoningSummaryVerbosity$outboundSchema, } from "./reasoningsummaryverbosity.js";
import { ResponseFormatJSONSchema$outboundSchema, } from "./responseformatjsonschema.js";
import { ResponseFormatTextGrammar$outboundSchema, } from "./responseformattextgrammar.js";
import { ToolDefinitionJson$outboundSchema, } from "./tooldefinitionjson.js";
export const Effort = {
    None: "none",
    Minimal: "minimal",
    Low: "low",
    Medium: "medium",
    High: "high",
};
/** @internal */
export const Effort$outboundSchema = openEnums
    .outboundSchema(Effort);
/** @internal */
export const Reasoning$outboundSchema = z.object({
    effort: z.nullable(Effort$outboundSchema).optional(),
    summary: z.nullable(ReasoningSummaryVerbosity$outboundSchema).optional(),
});
export function reasoningToJSON(reasoning) {
    return JSON.stringify(Reasoning$outboundSchema.parse(reasoning));
}
/** @internal */
export const ChatGenerationParamsResponseFormatPython$outboundSchema = z.object({
    type: z.literal("python"),
});
export function chatGenerationParamsResponseFormatPythonToJSON(chatGenerationParamsResponseFormatPython) {
    return JSON.stringify(ChatGenerationParamsResponseFormatPython$outboundSchema.parse(chatGenerationParamsResponseFormatPython));
}
/** @internal */
export const ChatGenerationParamsResponseFormatJSONObject$outboundSchema = z.object({
    type: z.literal("json_object"),
});
export function chatGenerationParamsResponseFormatJSONObjectToJSON(chatGenerationParamsResponseFormatJSONObject) {
    return JSON.stringify(ChatGenerationParamsResponseFormatJSONObject$outboundSchema.parse(chatGenerationParamsResponseFormatJSONObject));
}
/** @internal */
export const ChatGenerationParamsResponseFormatText$outboundSchema = z.object({
    type: z.literal("text"),
});
export function chatGenerationParamsResponseFormatTextToJSON(chatGenerationParamsResponseFormatText) {
    return JSON.stringify(ChatGenerationParamsResponseFormatText$outboundSchema.parse(chatGenerationParamsResponseFormatText));
}
/** @internal */
export const ChatGenerationParamsResponseFormatUnion$outboundSchema = z.union([
    ResponseFormatJSONSchema$outboundSchema,
    ResponseFormatTextGrammar$outboundSchema,
    z.lazy(() => ChatGenerationParamsResponseFormatText$outboundSchema),
    z.lazy(() => ChatGenerationParamsResponseFormatJSONObject$outboundSchema),
    z.lazy(() => ChatGenerationParamsResponseFormatPython$outboundSchema),
]);
export function chatGenerationParamsResponseFormatUnionToJSON(chatGenerationParamsResponseFormatUnion) {
    return JSON.stringify(ChatGenerationParamsResponseFormatUnion$outboundSchema.parse(chatGenerationParamsResponseFormatUnion));
}
/** @internal */
export const ChatGenerationParamsStop$outboundSchema = z.union([z.string(), z.array(z.string())]);
export function chatGenerationParamsStopToJSON(chatGenerationParamsStop) {
    return JSON.stringify(ChatGenerationParamsStop$outboundSchema.parse(chatGenerationParamsStop));
}
/** @internal */
export const ChatGenerationParams$outboundSchema = z.object({
    messages: z.array(Message$outboundSchema),
    model: z.string().optional(),
    models: z.array(z.string()).optional(),
    frequencyPenalty: z.nullable(z.number()).optional(),
    logitBias: z.nullable(z.record(z.string(), z.number())).optional(),
    logprobs: z.nullable(z.boolean()).optional(),
    topLogprobs: z.nullable(z.number()).optional(),
    maxCompletionTokens: z.nullable(z.number()).optional(),
    maxTokens: z.nullable(z.number()).optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    presencePenalty: z.nullable(z.number()).optional(),
    reasoning: z.lazy(() => Reasoning$outboundSchema).optional(),
    responseFormat: z.union([
        ResponseFormatJSONSchema$outboundSchema,
        ResponseFormatTextGrammar$outboundSchema,
        z.lazy(() => ChatGenerationParamsResponseFormatText$outboundSchema),
        z.lazy(() => ChatGenerationParamsResponseFormatJSONObject$outboundSchema),
        z.lazy(() => ChatGenerationParamsResponseFormatPython$outboundSchema),
    ]).optional(),
    seed: z.nullable(z.int()).optional(),
    stop: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
    stream: z.boolean().default(false),
    streamOptions: z.nullable(ChatStreamOptions$outboundSchema).optional(),
    temperature: z.nullable(z.number()).optional(),
    toolChoice: z.any().optional(),
    tools: z.array(ToolDefinitionJson$outboundSchema).optional(),
    topP: z.nullable(z.number()).optional(),
    user: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        frequencyPenalty: "frequency_penalty",
        logitBias: "logit_bias",
        topLogprobs: "top_logprobs",
        maxCompletionTokens: "max_completion_tokens",
        maxTokens: "max_tokens",
        presencePenalty: "presence_penalty",
        responseFormat: "response_format",
        streamOptions: "stream_options",
        toolChoice: "tool_choice",
        topP: "top_p",
    });
});
export function chatGenerationParamsToJSON(chatGenerationParams) {
    return JSON.stringify(ChatGenerationParams$outboundSchema.parse(chatGenerationParams));
}
//# sourceMappingURL=chatgenerationparams.js.map