/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { DataCollection$outboundSchema, } from "./datacollection.js";
import { OpenAIResponsesIncludable$outboundSchema, } from "./openairesponsesincludable.js";
import { OpenAIResponsesPrompt$outboundSchema, } from "./openairesponsesprompt.js";
import { OpenAIResponsesToolChoiceUnion$outboundSchema, } from "./openairesponsestoolchoiceunion.js";
import { OpenResponsesInput$outboundSchema, } from "./openresponsesinput.js";
import { OpenResponsesReasoningConfig$outboundSchema, } from "./openresponsesreasoningconfig.js";
import { OpenResponsesResponseText$outboundSchema, } from "./openresponsesresponsetext.js";
import { OpenResponsesWebSearch20250826Tool$outboundSchema, } from "./openresponseswebsearch20250826tool.js";
import { OpenResponsesWebSearchPreview20250311Tool$outboundSchema, } from "./openresponseswebsearchpreview20250311tool.js";
import { OpenResponsesWebSearchPreviewTool$outboundSchema, } from "./openresponseswebsearchpreviewtool.js";
import { OpenResponsesWebSearchTool$outboundSchema, } from "./openresponseswebsearchtool.js";
import { ProviderName$outboundSchema } from "./providername.js";
import { ProviderSort$outboundSchema } from "./providersort.js";
import { Quantization$outboundSchema } from "./quantization.js";
export const OpenResponsesRequestType = {
    Function: "function",
};
export const ServiceTier = {
    Auto: "auto",
    Default: "default",
    Flex: "flex",
    Priority: "priority",
    Scale: "scale",
};
export const Truncation = {
    Auto: "auto",
    Disabled: "disabled",
};
export const IdFileParser = {
    FileParser: "file-parser",
};
export const PdfEngine = {
    MistralOcr: "mistral-ocr",
    PdfText: "pdf-text",
    Native: "native",
};
export const IdWeb = {
    Web: "web",
};
export const Engine = {
    Native: "native",
    Exa: "exa",
};
export const IdModeration = {
    Moderation: "moderation",
};
/** @internal */
export const OpenResponsesRequestType$outboundSchema = z.enum(OpenResponsesRequestType);
/** @internal */
export const OpenResponsesRequestToolFunction$outboundSchema = z.object({
    type: OpenResponsesRequestType$outboundSchema,
    name: z.string(),
    description: z.nullable(z.string()).optional(),
    strict: z.nullable(z.boolean()).optional(),
    parameters: z.nullable(z.record(z.string(), z.nullable(z.any()))),
});
export function openResponsesRequestToolFunctionToJSON(openResponsesRequestToolFunction) {
    return JSON.stringify(OpenResponsesRequestToolFunction$outboundSchema.parse(openResponsesRequestToolFunction));
}
/** @internal */
export const OpenResponsesRequestToolUnion$outboundSchema = z.union([
    z.lazy(() => OpenResponsesRequestToolFunction$outboundSchema),
    OpenResponsesWebSearchPreviewTool$outboundSchema,
    OpenResponsesWebSearchPreview20250311Tool$outboundSchema,
    OpenResponsesWebSearchTool$outboundSchema,
    OpenResponsesWebSearch20250826Tool$outboundSchema,
]);
export function openResponsesRequestToolUnionToJSON(openResponsesRequestToolUnion) {
    return JSON.stringify(OpenResponsesRequestToolUnion$outboundSchema.parse(openResponsesRequestToolUnion));
}
/** @internal */
export const ServiceTier$outboundSchema = openEnums.outboundSchema(ServiceTier);
/** @internal */
export const Truncation$outboundSchema = openEnums.outboundSchema(Truncation);
/** @internal */
export const Order$outboundSchema = z.union([
    ProviderName$outboundSchema,
    z.string(),
]);
export function orderToJSON(order) {
    return JSON.stringify(Order$outboundSchema.parse(order));
}
/** @internal */
export const Only$outboundSchema = z.union([
    ProviderName$outboundSchema,
    z.string(),
]);
export function onlyToJSON(only) {
    return JSON.stringify(Only$outboundSchema.parse(only));
}
/** @internal */
export const Ignore$outboundSchema = z
    .union([ProviderName$outboundSchema, z.string()]);
export function ignoreToJSON(ignore) {
    return JSON.stringify(Ignore$outboundSchema.parse(ignore));
}
/** @internal */
export const MaxPrice$outboundSchema = z
    .object({
    prompt: z.any().optional(),
    completion: z.any().optional(),
    image: z.any().optional(),
    audio: z.any().optional(),
    request: z.any().optional(),
});
export function maxPriceToJSON(maxPrice) {
    return JSON.stringify(MaxPrice$outboundSchema.parse(maxPrice));
}
/** @internal */
export const Provider$outboundSchema = z
    .object({
    allowFallbacks: z.nullable(z.boolean()).optional(),
    requireParameters: z.nullable(z.boolean()).optional(),
    dataCollection: z.nullable(DataCollection$outboundSchema).optional(),
    zdr: z.nullable(z.boolean()).optional(),
    enforceDistillableText: z.nullable(z.boolean()).optional(),
    order: z.nullable(z.array(z.union([ProviderName$outboundSchema, z.string()]))).optional(),
    only: z.nullable(z.array(z.union([ProviderName$outboundSchema, z.string()]))).optional(),
    ignore: z.nullable(z.array(z.union([ProviderName$outboundSchema, z.string()]))).optional(),
    quantizations: z.nullable(z.array(Quantization$outboundSchema)).optional(),
    sort: z.nullable(ProviderSort$outboundSchema).optional(),
    maxPrice: z.lazy(() => MaxPrice$outboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        allowFallbacks: "allow_fallbacks",
        requireParameters: "require_parameters",
        dataCollection: "data_collection",
        enforceDistillableText: "enforce_distillable_text",
        maxPrice: "max_price",
    });
});
export function providerToJSON(provider) {
    return JSON.stringify(Provider$outboundSchema.parse(provider));
}
/** @internal */
export const IdFileParser$outboundSchema = z
    .enum(IdFileParser);
/** @internal */
export const PdfEngine$outboundSchema = openEnums
    .outboundSchema(PdfEngine);
/** @internal */
export const Pdf$outboundSchema = z.object({
    engine: PdfEngine$outboundSchema.optional(),
});
export function pdfToJSON(pdf) {
    return JSON.stringify(Pdf$outboundSchema.parse(pdf));
}
/** @internal */
export const PluginFileParser$outboundSchema = z.object({
    id: IdFileParser$outboundSchema,
    maxFiles: z.number().optional(),
    pdf: z.lazy(() => Pdf$outboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        maxFiles: "max_files",
    });
});
export function pluginFileParserToJSON(pluginFileParser) {
    return JSON.stringify(PluginFileParser$outboundSchema.parse(pluginFileParser));
}
/** @internal */
export const IdWeb$outboundSchema = z.enum(IdWeb);
/** @internal */
export const Engine$outboundSchema = openEnums
    .outboundSchema(Engine);
/** @internal */
export const PluginWeb$outboundSchema = z.object({
    id: IdWeb$outboundSchema,
    maxResults: z.number().optional(),
    searchPrompt: z.string().optional(),
    engine: Engine$outboundSchema.optional(),
}).transform((v) => {
    return remap$(v, {
        maxResults: "max_results",
        searchPrompt: "search_prompt",
    });
});
export function pluginWebToJSON(pluginWeb) {
    return JSON.stringify(PluginWeb$outboundSchema.parse(pluginWeb));
}
/** @internal */
export const IdModeration$outboundSchema = z
    .enum(IdModeration);
/** @internal */
export const PluginModeration$outboundSchema = z.object({
    id: IdModeration$outboundSchema,
});
export function pluginModerationToJSON(pluginModeration) {
    return JSON.stringify(PluginModeration$outboundSchema.parse(pluginModeration));
}
/** @internal */
export const Plugin$outboundSchema = z
    .union([
    z.lazy(() => PluginModeration$outboundSchema),
    z.lazy(() => PluginWeb$outboundSchema),
    z.lazy(() => PluginFileParser$outboundSchema),
]);
export function pluginToJSON(plugin) {
    return JSON.stringify(Plugin$outboundSchema.parse(plugin));
}
/** @internal */
export const OpenResponsesRequest$outboundSchema = z.object({
    input: OpenResponsesInput$outboundSchema.optional(),
    instructions: z.nullable(z.string()).optional(),
    metadata: z.nullable(z.record(z.string(), z.string())).optional(),
    tools: z.array(z.union([
        z.lazy(() => OpenResponsesRequestToolFunction$outboundSchema),
        OpenResponsesWebSearchPreviewTool$outboundSchema,
        OpenResponsesWebSearchPreview20250311Tool$outboundSchema,
        OpenResponsesWebSearchTool$outboundSchema,
        OpenResponsesWebSearch20250826Tool$outboundSchema,
    ])).optional(),
    toolChoice: OpenAIResponsesToolChoiceUnion$outboundSchema.optional(),
    parallelToolCalls: z.nullable(z.boolean()).optional(),
    model: z.string().optional(),
    models: z.array(z.string()).optional(),
    text: OpenResponsesResponseText$outboundSchema.optional(),
    reasoning: z.nullable(OpenResponsesReasoningConfig$outboundSchema).optional(),
    maxOutputTokens: z.nullable(z.number()).optional(),
    temperature: z.nullable(z.number()).optional(),
    topP: z.nullable(z.number()).optional(),
    topK: z.number().optional(),
    promptCacheKey: z.nullable(z.string()).optional(),
    previousResponseId: z.nullable(z.string()).optional(),
    prompt: z.nullable(OpenAIResponsesPrompt$outboundSchema).optional(),
    include: z.nullable(z.array(OpenAIResponsesIncludable$outboundSchema))
        .optional(),
    background: z.nullable(z.boolean()).optional(),
    safetyIdentifier: z.nullable(z.string()).optional(),
    store: z.nullable(z.boolean()).optional(),
    serviceTier: z.nullable(ServiceTier$outboundSchema).optional(),
    truncation: z.nullable(Truncation$outboundSchema).optional(),
    stream: z.boolean().default(false),
    provider: z.nullable(z.lazy(() => Provider$outboundSchema)).optional(),
    plugins: z.array(z.union([
        z.lazy(() => PluginModeration$outboundSchema),
        z.lazy(() => PluginWeb$outboundSchema),
        z.lazy(() => PluginFileParser$outboundSchema),
    ])).optional(),
    user: z.string().optional(),
}).transform((v) => {
    return remap$(v, {
        toolChoice: "tool_choice",
        parallelToolCalls: "parallel_tool_calls",
        maxOutputTokens: "max_output_tokens",
        topP: "top_p",
        topK: "top_k",
        promptCacheKey: "prompt_cache_key",
        previousResponseId: "previous_response_id",
        safetyIdentifier: "safety_identifier",
        serviceTier: "service_tier",
    });
});
export function openResponsesRequestToJSON(openResponsesRequest) {
    return JSON.stringify(OpenResponsesRequest$outboundSchema.parse(openResponsesRequest));
}
//# sourceMappingURL=openresponsesrequest.js.map