/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { ClientSDK } from "../lib/sdks.js";
import { Responses } from "./responses.js";
export class Beta extends ClientSDK {
    get responses() {
        return (this._responses ?? (this._responses = new Responses(this._options)));
    }
}
//# sourceMappingURL=beta.js.map