/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { VideoURL$inboundSchema, VideoURL$outboundSchema, } from "./videourl.js";
/** @internal */
export const ChatMessageContentItemVideoVideoUrlVideoUrl$inboundSchema = z.object({
    url: z.string(),
});
/** @internal */
export const ChatMessageContentItemVideoVideoUrlVideoUrl$outboundSchema = z.object({
    url: z.string(),
});
export function chatMessageContentItemVideoVideoUrlVideoUrlToJSON(chatMessageContentItemVideoVideoUrlVideoUrl) {
    return JSON.stringify(ChatMessageContentItemVideoVideoUrlVideoUrl$outboundSchema.parse(chatMessageContentItemVideoVideoUrlVideoUrl));
}
export function chatMessageContentItemVideoVideoUrlVideoUrlFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItemVideoVideoUrlVideoUrl$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItemVideoVideoUrlVideoUrl' from JSON`);
}
/** @internal */
export const ChatMessageContentItemVideoVideoURL$inboundSchema = z.object({
    type: z.literal("video_url"),
    video_url: z.lazy(() => ChatMessageContentItemVideoVideoUrlVideoUrl$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "video_url": "videoUrl",
    });
});
/** @internal */
export const ChatMessageContentItemVideoVideoURL$outboundSchema = z.object({
    type: z.literal("video_url"),
    videoUrl: z.lazy(() => ChatMessageContentItemVideoVideoUrlVideoUrl$outboundSchema),
}).transform((v) => {
    return remap$(v, {
        videoUrl: "video_url",
    });
});
export function chatMessageContentItemVideoVideoURLToJSON(chatMessageContentItemVideoVideoURL) {
    return JSON.stringify(ChatMessageContentItemVideoVideoURL$outboundSchema.parse(chatMessageContentItemVideoVideoURL));
}
export function chatMessageContentItemVideoVideoURLFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItemVideoVideoURL$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItemVideoVideoURL' from JSON`);
}
/** @internal */
export const ChatMessageContentItemVideoInputVideo$inboundSchema = z.object({
    type: z.literal("input_video"),
    video_url: VideoURL$inboundSchema,
}).transform((v) => {
    return remap$(v, {
        "video_url": "videoUrl",
    });
});
/** @internal */
export const ChatMessageContentItemVideoInputVideo$outboundSchema = z.object({
    type: z.literal("input_video"),
    videoUrl: VideoURL$outboundSchema,
}).transform((v) => {
    return remap$(v, {
        videoUrl: "video_url",
    });
});
export function chatMessageContentItemVideoInputVideoToJSON(chatMessageContentItemVideoInputVideo) {
    return JSON.stringify(ChatMessageContentItemVideoInputVideo$outboundSchema.parse(chatMessageContentItemVideoInputVideo));
}
export function chatMessageContentItemVideoInputVideoFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItemVideoInputVideo$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItemVideoInputVideo' from JSON`);
}
/** @internal */
export const ChatMessageContentItemVideo$inboundSchema = z.union([
    z.lazy(() => ChatMessageContentItemVideoInputVideo$inboundSchema),
    z.lazy(() => ChatMessageContentItemVideoVideoURL$inboundSchema),
]);
/** @internal */
export const ChatMessageContentItemVideo$outboundSchema = z.union([
    z.lazy(() => ChatMessageContentItemVideoInputVideo$outboundSchema),
    z.lazy(() => ChatMessageContentItemVideoVideoURL$outboundSchema),
]);
export function chatMessageContentItemVideoToJSON(chatMessageContentItemVideo) {
    return JSON.stringify(ChatMessageContentItemVideo$outboundSchema.parse(chatMessageContentItemVideo));
}
export function chatMessageContentItemVideoFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItemVideo$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItemVideo' from JSON`);
}
//# sourceMappingURL=chatmessagecontentitemvideo.js.map