/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as openEnums from "../types/enums.js";
export const OutputModality = {
    Text: "text",
    Image: "image",
    Embeddings: "embeddings",
};
/** @internal */
export const OutputModality$inboundSchema = openEnums.inboundSchema(OutputModality);
//# sourceMappingURL=outputmodality.js.map