/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import * as models from "../index.js";
/** @internal */
export const ListEndpointsZdrResponse$inboundSchema = z.object({
    data: z.array(models.PublicEndpoint$inboundSchema),
});
export function listEndpointsZdrResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListEndpointsZdrResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListEndpointsZdrResponse' from JSON`);
}
//# sourceMappingURL=listendpointszdr.js.map