/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
export const ResponsesFormatTextJSONSchemaConfigType = {
    JsonSchema: "json_schema",
};
/** @internal */
export const ResponsesFormatTextJSONSchemaConfigType$inboundSchema = z.enum(ResponsesFormatTextJSONSchemaConfigType);
/** @internal */
export const ResponsesFormatTextJSONSchemaConfigType$outboundSchema = ResponsesFormatTextJSONSchemaConfigType$inboundSchema;
/** @internal */
export const ResponsesFormatTextJSONSchemaConfig$inboundSchema = z.object({
    type: ResponsesFormatTextJSONSchemaConfigType$inboundSchema,
    name: z.string(),
    description: z.string().optional(),
    strict: z.nullable(z.boolean()).optional(),
    schema: z.record(z.string(), z.nullable(z.any())),
});
/** @internal */
export const ResponsesFormatTextJSONSchemaConfig$outboundSchema = z.object({
    type: ResponsesFormatTextJSONSchemaConfigType$outboundSchema,
    name: z.string(),
    description: z.string().optional(),
    strict: z.nullable(z.boolean()).optional(),
    schema: z.record(z.string(), z.nullable(z.any())),
});
export function responsesFormatTextJSONSchemaConfigToJSON(responsesFormatTextJSONSchemaConfig) {
    return JSON.stringify(ResponsesFormatTextJSONSchemaConfig$outboundSchema.parse(responsesFormatTextJSONSchemaConfig));
}
export function responsesFormatTextJSONSchemaConfigFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponsesFormatTextJSONSchemaConfig$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponsesFormatTextJSONSchemaConfig' from JSON`);
}
//# sourceMappingURL=responsesformattextjsonschemaconfig.js.map