/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
/** @internal */
export const ResponseFormatTextGrammar$outboundSchema = z.object({
    type: z.literal("grammar"),
    grammar: z.string(),
});
export function responseFormatTextGrammarToJSON(responseFormatTextGrammar) {
    return JSON.stringify(ResponseFormatTextGrammar$outboundSchema.parse(responseFormatTextGrammar));
}
//# sourceMappingURL=responseformattextgrammar.js.map