/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
/** @internal */
export const NotFoundResponseErrorData$inboundSchema = z.object({
    code: z.int(),
    message: z.string(),
    metadata: z.nullable(z.record(z.string(), z.nullable(z.any()))).optional(),
});
export function notFoundResponseErrorDataFromJSON(jsonString) {
    return safeParse(jsonString, (x) => NotFoundResponseErrorData$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'NotFoundResponseErrorData' from JSON`);
}
//# sourceMappingURL=notfoundresponseerrordata.js.map