/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesImageGenCallPartialImageType = {
    ResponseImageGenerationCallPartialImage: "response.image_generation_call.partial_image",
};
/** @internal */
export const OpenResponsesImageGenCallPartialImageType$inboundSchema = z.enum(OpenResponsesImageGenCallPartialImageType);
/** @internal */
export const OpenResponsesImageGenCallPartialImage$inboundSchema = z.object({
    type: OpenResponsesImageGenCallPartialImageType$inboundSchema,
    item_id: z.string(),
    output_index: z.number(),
    sequence_number: z.number(),
    partial_image_b64: z.string(),
    partial_image_index: z.number(),
}).transform((v) => {
    return remap$(v, {
        "item_id": "itemId",
        "output_index": "outputIndex",
        "sequence_number": "sequenceNumber",
        "partial_image_b64": "partialImageB64",
        "partial_image_index": "partialImageIndex",
    });
});
export function openResponsesImageGenCallPartialImageFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesImageGenCallPartialImage$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesImageGenCallPartialImage' from JSON`);
}
//# sourceMappingURL=openresponsesimagegencallpartialimage.js.map