/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { OpenAIResponsesAnnotation$inboundSchema, OpenAIResponsesAnnotation$outboundSchema, } from "./openairesponsesannotation.js";
export const ResponseOutputTextType = {
    OutputText: "output_text",
};
/** @internal */
export const ResponseOutputTextType$inboundSchema = z.enum(ResponseOutputTextType);
/** @internal */
export const ResponseOutputTextType$outboundSchema = ResponseOutputTextType$inboundSchema;
/** @internal */
export const ResponseOutputText$inboundSchema = z.object({
    type: ResponseOutputTextType$inboundSchema,
    text: z.string(),
    annotations: z.array(OpenAIResponsesAnnotation$inboundSchema).optional(),
});
/** @internal */
export const ResponseOutputText$outboundSchema = z.object({
    type: ResponseOutputTextType$outboundSchema,
    text: z.string(),
    annotations: z.array(OpenAIResponsesAnnotation$outboundSchema).optional(),
});
export function responseOutputTextToJSON(responseOutputText) {
    return JSON.stringify(ResponseOutputText$outboundSchema.parse(responseOutputText));
}
export function responseOutputTextFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponseOutputText$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponseOutputText' from JSON`);
}
//# sourceMappingURL=responseoutputtext.js.map