/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as openEnums from "../types/enums.js";
export const InputModality = {
    Text: "text",
    Image: "image",
    File: "file",
    Audio: "audio",
    Video: "video",
};
/** @internal */
export const InputModality$inboundSchema = openEnums.inboundSchema(InputModality);
//# sourceMappingURL=inputmodality.js.map