/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
/** @internal */
export const VideoURL$inboundSchema = z.object({
    url: z.string(),
});
/** @internal */
export const VideoURL$outboundSchema = z
    .object({
    url: z.string(),
});
export function videoURLToJSON(videoURL) {
    return JSON.stringify(VideoURL$outboundSchema.parse(videoURL));
}
export function videoURLFromJSON(jsonString) {
    return safeParse(jsonString, (x) => VideoURL$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'VideoURL' from JSON`);
}
//# sourceMappingURL=videourl.js.map