/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesReasoningDoneEventType = {
    ResponseReasoningTextDone: "response.reasoning_text.done",
};
/** @internal */
export const OpenResponsesReasoningDoneEventType$inboundSchema = z.enum(OpenResponsesReasoningDoneEventType);
/** @internal */
export const OpenResponsesReasoningDoneEvent$inboundSchema = z.object({
    type: OpenResponsesReasoningDoneEventType$inboundSchema,
    output_index: z.number(),
    item_id: z.string(),
    content_index: z.number(),
    text: z.string(),
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "output_index": "outputIndex",
        "item_id": "itemId",
        "content_index": "contentIndex",
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesReasoningDoneEventFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesReasoningDoneEvent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesReasoningDoneEvent' from JSON`);
}
//# sourceMappingURL=openresponsesreasoningdoneevent.js.map