/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const FilePathType = {
    FilePath: "file_path",
};
/** @internal */
export const FilePathType$inboundSchema = z
    .enum(FilePathType);
/** @internal */
export const FilePathType$outboundSchema = FilePathType$inboundSchema;
/** @internal */
export const FilePath$inboundSchema = z.object({
    type: FilePathType$inboundSchema,
    file_id: z.string(),
    index: z.number(),
}).transform((v) => {
    return remap$(v, {
        "file_id": "fileId",
    });
});
/** @internal */
export const FilePath$outboundSchema = z
    .object({
    type: FilePathType$outboundSchema,
    fileId: z.string(),
    index: z.number(),
}).transform((v) => {
    return remap$(v, {
        fileId: "file_id",
    });
});
export function filePathToJSON(filePath) {
    return JSON.stringify(FilePath$outboundSchema.parse(filePath));
}
export function filePathFromJSON(jsonString) {
    return safeParse(jsonString, (x) => FilePath$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'FilePath' from JSON`);
}
//# sourceMappingURL=filepath.js.map