/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { betaResponsesSend } from "../funcs/betaResponsesSend.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class Responses extends ClientSDK {
    async send(request, options) {
        return unwrapAsync(betaResponsesSend(this, request, options));
    }
}
//# sourceMappingURL=responses.js.map