/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ResponsesSearchContextSize$inboundSchema, ResponsesSearchContextSize$outboundSchema, } from "./responsessearchcontextsize.js";
import { WebSearchPreviewToolUserLocation$inboundSchema, WebSearchPreviewToolUserLocation$outboundSchema, } from "./websearchpreviewtooluserlocation.js";
export const OpenResponsesWebSearchPreviewToolType = {
    WebSearchPreview: "web_search_preview",
};
/** @internal */
export const OpenResponsesWebSearchPreviewToolType$inboundSchema = z.enum(OpenResponsesWebSearchPreviewToolType);
/** @internal */
export const OpenResponsesWebSearchPreviewToolType$outboundSchema = OpenResponsesWebSearchPreviewToolType$inboundSchema;
/** @internal */
export const OpenResponsesWebSearchPreviewTool$inboundSchema = z.object({
    type: OpenResponsesWebSearchPreviewToolType$inboundSchema,
    search_context_size: ResponsesSearchContextSize$inboundSchema.optional(),
    user_location: z.nullable(WebSearchPreviewToolUserLocation$inboundSchema)
        .optional(),
}).transform((v) => {
    return remap$(v, {
        "search_context_size": "searchContextSize",
        "user_location": "userLocation",
    });
});
/** @internal */
export const OpenResponsesWebSearchPreviewTool$outboundSchema = z.object({
    type: OpenResponsesWebSearchPreviewToolType$outboundSchema,
    searchContextSize: ResponsesSearchContextSize$outboundSchema.optional(),
    userLocation: z.nullable(WebSearchPreviewToolUserLocation$outboundSchema)
        .optional(),
}).transform((v) => {
    return remap$(v, {
        searchContextSize: "search_context_size",
        userLocation: "user_location",
    });
});
export function openResponsesWebSearchPreviewToolToJSON(openResponsesWebSearchPreviewTool) {
    return JSON.stringify(OpenResponsesWebSearchPreviewTool$outboundSchema.parse(openResponsesWebSearchPreviewTool));
}
export function openResponsesWebSearchPreviewToolFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesWebSearchPreviewTool$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesWebSearchPreviewTool' from JSON`);
}
//# sourceMappingURL=openresponseswebsearchpreviewtool.js.map