/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
/** @internal */
export const TopProviderInfo$inboundSchema = z.object({
    context_length: z.nullable(z.number()).optional(),
    max_completion_tokens: z.nullable(z.number()).optional(),
    is_moderated: z.boolean(),
}).transform((v) => {
    return remap$(v, {
        "context_length": "contextLength",
        "max_completion_tokens": "maxCompletionTokens",
        "is_moderated": "isModerated",
    });
});
export function topProviderInfoFromJSON(jsonString) {
    return safeParse(jsonString, (x) => TopProviderInfo$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'TopProviderInfo' from JSON`);
}
//# sourceMappingURL=topproviderinfo.js.map