/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as openEnums from "../types/enums.js";
/**
 * The sorting strategy to use for this request, if "order" is not specified. When set, no load balancing is performed.
 */
export const ProviderSort = {
    Price: "price",
    Throughput: "throughput",
    Latency: "latency",
};
/** @internal */
export const ProviderSort$outboundSchema = openEnums.outboundSchema(ProviderSort);
//# sourceMappingURL=providersort.js.map