/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { AssistantMessage$inboundSchema, } from "./assistantmessage.js";
import { ChatMessageTokenLogprobs$inboundSchema, } from "./chatmessagetokenlogprobs.js";
import { ChatStreamingMessageChunk$inboundSchema, } from "./chatstreamingmessagechunk.js";
export const ChatCompletionFinishReason = {
    ToolCalls: "tool_calls",
    Stop: "stop",
    Length: "length",
    ContentFilter: "content_filter",
    Error: "error",
};
/** @internal */
export const ChatCompletionFinishReason$inboundSchema = openEnums.inboundSchema(ChatCompletionFinishReason);
/** @internal */
export const ChatResponseChoice$inboundSchema = z.object({
    finish_reason: z.nullable(ChatCompletionFinishReason$inboundSchema),
    index: z.number(),
    message: AssistantMessage$inboundSchema,
    logprobs: z.nullable(ChatMessageTokenLogprobs$inboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        "finish_reason": "finishReason",
    });
});
export function chatResponseChoiceFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatResponseChoice$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatResponseChoice' from JSON`);
}
/** @internal */
export const ChatStreamingChoice$inboundSchema = z.object({
    delta: ChatStreamingMessageChunk$inboundSchema,
    finish_reason: z.nullable(ChatCompletionFinishReason$inboundSchema),
    index: z.number(),
    logprobs: z.nullable(ChatMessageTokenLogprobs$inboundSchema).optional(),
}).transform((v) => {
    return remap$(v, {
        "finish_reason": "finishReason",
    });
});
export function chatStreamingChoiceFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatStreamingChoice$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatStreamingChoice' from JSON`);
}
//# sourceMappingURL=chatresponsechoice.js.map