/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as openEnums from "../types/enums.js";
export const ImageGenerationStatus = {
    InProgress: "in_progress",
    Completed: "completed",
    Generating: "generating",
    Failed: "failed",
};
/** @internal */
export const ImageGenerationStatus$inboundSchema = openEnums.inboundSchema(ImageGenerationStatus);
/** @internal */
export const ImageGenerationStatus$outboundSchema = openEnums.outboundSchema(ImageGenerationStatus);
//# sourceMappingURL=imagegenerationstatus.js.map