/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
export const OpenAIResponsesRefusalContentType = {
    Refusal: "refusal",
};
/** @internal */
export const OpenAIResponsesRefusalContentType$inboundSchema = z.enum(OpenAIResponsesRefusalContentType);
/** @internal */
export const OpenAIResponsesRefusalContentType$outboundSchema = OpenAIResponsesRefusalContentType$inboundSchema;
/** @internal */
export const OpenAIResponsesRefusalContent$inboundSchema = z.object({
    type: OpenAIResponsesRefusalContentType$inboundSchema,
    refusal: z.string(),
});
/** @internal */
export const OpenAIResponsesRefusalContent$outboundSchema = z.object({
    type: OpenAIResponsesRefusalContentType$outboundSchema,
    refusal: z.string(),
});
export function openAIResponsesRefusalContentToJSON(openAIResponsesRefusalContent) {
    return JSON.stringify(OpenAIResponsesRefusalContent$outboundSchema.parse(openAIResponsesRefusalContent));
}
export function openAIResponsesRefusalContentFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenAIResponsesRefusalContent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenAIResponsesRefusalContent' from JSON`);
}
//# sourceMappingURL=openairesponsesrefusalcontent.js.map