/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as openEnums from "../types/enums.js";
export const ToolCallStatus = {
    InProgress: "in_progress",
    Completed: "completed",
    Incomplete: "incomplete",
};
/** @internal */
export const ToolCallStatus$inboundSchema = openEnums.inboundSchema(ToolCallStatus);
/** @internal */
export const ToolCallStatus$outboundSchema = openEnums.outboundSchema(ToolCallStatus);
//# sourceMappingURL=toolcallstatus.js.map