/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { generationsGetGeneration } from "../funcs/generationsGetGeneration.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class Generations extends ClientSDK {
    /**
     * Get request & usage metadata for a generation
     */
    async getGeneration(request, options) {
        return unwrapAsync(generationsGetGeneration(this, request, options));
    }
}
//# sourceMappingURL=generations.js.map