/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { providersList } from "../funcs/providersList.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class Providers extends ClientSDK {
    /**
     * List all providers
     */
    async list(options) {
        return unwrapAsync(providersList(this, options));
    }
}
//# sourceMappingURL=providers.js.map