/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ReasoningSummaryText$inboundSchema, } from "./reasoningsummarytext.js";
export const OpenResponsesReasoningSummaryPartAddedEventType = {
    ResponseReasoningSummaryPartAdded: "response.reasoning_summary_part.added",
};
/** @internal */
export const OpenResponsesReasoningSummaryPartAddedEventType$inboundSchema = z.enum(OpenResponsesReasoningSummaryPartAddedEventType);
/** @internal */
export const OpenResponsesReasoningSummaryPartAddedEvent$inboundSchema = z.object({
    type: OpenResponsesReasoningSummaryPartAddedEventType$inboundSchema,
    output_index: z.number(),
    item_id: z.string(),
    summary_index: z.number(),
    part: ReasoningSummaryText$inboundSchema,
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "output_index": "outputIndex",
        "item_id": "itemId",
        "summary_index": "summaryIndex",
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesReasoningSummaryPartAddedEventFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesReasoningSummaryPartAddedEvent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesReasoningSummaryPartAddedEvent' from JSON`);
}
//# sourceMappingURL=openresponsesreasoningsummarypartaddedevent.js.map