/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesImageGenCallCompletedType = {
    ResponseImageGenerationCallCompleted: "response.image_generation_call.completed",
};
/** @internal */
export const OpenResponsesImageGenCallCompletedType$inboundSchema = z.enum(OpenResponsesImageGenCallCompletedType);
/** @internal */
export const OpenResponsesImageGenCallCompleted$inboundSchema = z.object({
    type: OpenResponsesImageGenCallCompletedType$inboundSchema,
    item_id: z.string(),
    output_index: z.number(),
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "item_id": "itemId",
        "output_index": "outputIndex",
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesImageGenCallCompletedFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesImageGenCallCompleted$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesImageGenCallCompleted' from JSON`);
}
//# sourceMappingURL=openresponsesimagegencallcompleted.js.map