/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { pathToFunc } from "./url.js";
/**
 * Production server
 */
export const ServerProduction = "production";
/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = {
    [ServerProduction]: "https://openrouter.ai/api/v1",
};
export function serverURLFromOptions(options) {
    let serverURL = options.serverURL;
    const params = {};
    if (!serverURL) {
        const server = options.server ?? ServerProduction;
        serverURL = ServerList[server] || "";
    }
    const u = pathToFunc(serverURL)(params);
    return new URL(u);
}
export const SDK_METADATA = {
    language: "typescript",
    openapiDocVersion: "1.0.0",
    sdkVersion: "0.1.27",
    genVersion: "2.760.2",
    userAgent: "speakeasy-sdk/typescript 0.1.27 2.760.2 1.0.0 @openrouter/sdk",
};
//# sourceMappingURL=config.js.map