/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesErrorEventType = {
    Error: "error",
};
/** @internal */
export const OpenResponsesErrorEventType$inboundSchema = z.enum(OpenResponsesErrorEventType);
/** @internal */
export const OpenResponsesErrorEvent$inboundSchema = z.object({
    type: OpenResponsesErrorEventType$inboundSchema,
    code: z.nullable(z.string()),
    message: z.string(),
    param: z.nullable(z.string()),
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesErrorEventFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesErrorEvent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesErrorEvent' from JSON`);
}
//# sourceMappingURL=openresponseserrorevent.js.map