/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesImageGenCallInProgressType = {
    ResponseImageGenerationCallInProgress: "response.image_generation_call.in_progress",
};
/** @internal */
export const OpenResponsesImageGenCallInProgressType$inboundSchema = z.enum(OpenResponsesImageGenCallInProgressType);
/** @internal */
export const OpenResponsesImageGenCallInProgress$inboundSchema = z.object({
    type: OpenResponsesImageGenCallInProgressType$inboundSchema,
    item_id: z.string(),
    output_index: z.number(),
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "item_id": "itemId",
        "output_index": "outputIndex",
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesImageGenCallInProgressFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesImageGenCallInProgress$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesImageGenCallInProgress' from JSON`);
}
//# sourceMappingURL=openresponsesimagegencallinprogress.js.map