/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as openEnums from "../types/enums.js";
export const ReasoningSummaryVerbosity = {
    Auto: "auto",
    Concise: "concise",
    Detailed: "detailed",
};
/** @internal */
export const ReasoningSummaryVerbosity$inboundSchema = openEnums.inboundSchema(ReasoningSummaryVerbosity);
/** @internal */
export const ReasoningSummaryVerbosity$outboundSchema = openEnums.outboundSchema(ReasoningSummaryVerbosity);
//# sourceMappingURL=reasoningsummaryverbosity.js.map