/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesReasoningSummaryTextDeltaEventType = {
    ResponseReasoningSummaryTextDelta: "response.reasoning_summary_text.delta",
};
/** @internal */
export const OpenResponsesReasoningSummaryTextDeltaEventType$inboundSchema = z.enum(OpenResponsesReasoningSummaryTextDeltaEventType);
/** @internal */
export const OpenResponsesReasoningSummaryTextDeltaEvent$inboundSchema = z.object({
    type: OpenResponsesReasoningSummaryTextDeltaEventType$inboundSchema,
    item_id: z.string(),
    output_index: z.number(),
    summary_index: z.number(),
    delta: z.string(),
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "item_id": "itemId",
        "output_index": "outputIndex",
        "summary_index": "summaryIndex",
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesReasoningSummaryTextDeltaEventFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesReasoningSummaryTextDeltaEvent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesReasoningSummaryTextDeltaEvent' from JSON`);
}
//# sourceMappingURL=openresponsesreasoningsummarytextdeltaevent.js.map