/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesReasoningSummaryTextDoneEventType = {
    ResponseReasoningSummaryTextDone: "response.reasoning_summary_text.done",
};
/** @internal */
export const OpenResponsesReasoningSummaryTextDoneEventType$inboundSchema = z.enum(OpenResponsesReasoningSummaryTextDoneEventType);
/** @internal */
export const OpenResponsesReasoningSummaryTextDoneEvent$inboundSchema = z.object({
    type: OpenResponsesReasoningSummaryTextDoneEventType$inboundSchema,
    item_id: z.string(),
    output_index: z.number(),
    summary_index: z.number(),
    text: z.string(),
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "item_id": "itemId",
        "output_index": "outputIndex",
        "summary_index": "summaryIndex",
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesReasoningSummaryTextDoneEventFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesReasoningSummaryTextDoneEvent$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesReasoningSummaryTextDoneEvent' from JSON`);
}
//# sourceMappingURL=openresponsesreasoningsummarytextdoneevent.js.map