/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
/** @internal */
export const ListModelsUserSecurity$outboundSchema = z.object({
    bearer: z.string(),
});
export function listModelsUserSecurityToJSON(listModelsUserSecurity) {
    return JSON.stringify(ListModelsUserSecurity$outboundSchema.parse(listModelsUserSecurity));
}
//# sourceMappingURL=listmodelsuser.js.map