/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
export const ResponseInputTextType = {
    InputText: "input_text",
};
/** @internal */
export const ResponseInputTextType$inboundSchema = z.enum(ResponseInputTextType);
/** @internal */
export const ResponseInputTextType$outboundSchema = ResponseInputTextType$inboundSchema;
/** @internal */
export const ResponseInputText$inboundSchema = z.object({
    type: ResponseInputTextType$inboundSchema,
    text: z.string(),
});
/** @internal */
export const ResponseInputText$outboundSchema = z.object({
    type: ResponseInputTextType$outboundSchema,
    text: z.string(),
});
export function responseInputTextToJSON(responseInputText) {
    return JSON.stringify(ResponseInputText$outboundSchema.parse(responseInputText));
}
export function responseInputTextFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponseInputText$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponseInputText' from JSON`);
}
//# sourceMappingURL=responseinputtext.js.map