/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
export const ResponseInputImageType = {
    InputImage: "input_image",
};
export const ResponseInputImageDetail = {
    Auto: "auto",
    High: "high",
    Low: "low",
};
/** @internal */
export const ResponseInputImageType$inboundSchema = z.enum(ResponseInputImageType);
/** @internal */
export const ResponseInputImageType$outboundSchema = ResponseInputImageType$inboundSchema;
/** @internal */
export const ResponseInputImageDetail$inboundSchema = openEnums.inboundSchema(ResponseInputImageDetail);
/** @internal */
export const ResponseInputImageDetail$outboundSchema = openEnums.outboundSchema(ResponseInputImageDetail);
/** @internal */
export const ResponseInputImage$inboundSchema = z.object({
    type: ResponseInputImageType$inboundSchema,
    detail: ResponseInputImageDetail$inboundSchema,
    image_url: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        "image_url": "imageUrl",
    });
});
/** @internal */
export const ResponseInputImage$outboundSchema = z.object({
    type: ResponseInputImageType$outboundSchema,
    detail: ResponseInputImageDetail$outboundSchema,
    imageUrl: z.nullable(z.string()).optional(),
}).transform((v) => {
    return remap$(v, {
        imageUrl: "image_url",
    });
});
export function responseInputImageToJSON(responseInputImage) {
    return JSON.stringify(ResponseInputImage$outboundSchema.parse(responseInputImage));
}
export function responseInputImageFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponseInputImage$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponseInputImage' from JSON`);
}
//# sourceMappingURL=responseinputimage.js.map