/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
/** @internal */
export const ChatMessageContentItemText$inboundSchema = z.object({
    type: z.literal("text"),
    text: z.string(),
});
/** @internal */
export const ChatMessageContentItemText$outboundSchema = z.object({
    type: z.literal("text"),
    text: z.string(),
});
export function chatMessageContentItemTextToJSON(chatMessageContentItemText) {
    return JSON.stringify(ChatMessageContentItemText$outboundSchema.parse(chatMessageContentItemText));
}
export function chatMessageContentItemTextFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItemText$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItemText' from JSON`);
}
//# sourceMappingURL=chatmessagecontentitemtext.js.map