/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { chatSend } from "../funcs/chatSend.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class Chat extends ClientSDK {
    async send(request, options) {
        return unwrapAsync(chatSend(this, request, options));
    }
}
//# sourceMappingURL=chat.js.map