/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
export const OpenResponsesImageGenCallGeneratingType = {
    ResponseImageGenerationCallGenerating: "response.image_generation_call.generating",
};
/** @internal */
export const OpenResponsesImageGenCallGeneratingType$inboundSchema = z.enum(OpenResponsesImageGenCallGeneratingType);
/** @internal */
export const OpenResponsesImageGenCallGenerating$inboundSchema = z.object({
    type: OpenResponsesImageGenCallGeneratingType$inboundSchema,
    item_id: z.string(),
    output_index: z.number(),
    sequence_number: z.number(),
}).transform((v) => {
    return remap$(v, {
        "item_id": "itemId",
        "output_index": "outputIndex",
        "sequence_number": "sequenceNumber",
    });
});
export function openResponsesImageGenCallGeneratingFromJSON(jsonString) {
    return safeParse(jsonString, (x) => OpenResponsesImageGenCallGenerating$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'OpenResponsesImageGenCallGenerating' from JSON`);
}
//# sourceMappingURL=openresponsesimagegencallgenerating.js.map