/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ResponsesImageGenerationCall$inboundSchema, } from "./responsesimagegenerationcall.js";
import { ResponsesOutputItemFileSearchCall$inboundSchema, } from "./responsesoutputitemfilesearchcall.js";
import { ResponsesOutputItemFunctionCall$inboundSchema, } from "./responsesoutputitemfunctioncall.js";
import { ResponsesOutputItemReasoning$inboundSchema, } from "./responsesoutputitemreasoning.js";
import { ResponsesOutputMessage$inboundSchema, } from "./responsesoutputmessage.js";
import { ResponsesWebSearchCallOutput$inboundSchema, } from "./responseswebsearchcalloutput.js";
/** @internal */
export const ResponsesOutputItem$inboundSchema = z.union([
    ResponsesOutputMessage$inboundSchema,
    ResponsesOutputItemFunctionCall$inboundSchema,
    ResponsesOutputItemFileSearchCall$inboundSchema,
    ResponsesOutputItemReasoning$inboundSchema,
    ResponsesWebSearchCallOutput$inboundSchema,
    ResponsesImageGenerationCall$inboundSchema,
]);
export function responsesOutputItemFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponsesOutputItem$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponsesOutputItem' from JSON`);
}
//# sourceMappingURL=responsesoutputitem.js.map