/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { CompletionLogprobs$inboundSchema, } from "./completionlogprobs.js";
export const CompletionFinishReason = {
    Stop: "stop",
    Length: "length",
    ContentFilter: "content_filter",
};
/** @internal */
export const CompletionFinishReason$inboundSchema = openEnums.inboundSchema(CompletionFinishReason);
/** @internal */
export const CompletionChoice$inboundSchema = z.object({
    text: z.string(),
    index: z.number(),
    logprobs: z.nullable(CompletionLogprobs$inboundSchema),
    finish_reason: z.nullable(CompletionFinishReason$inboundSchema),
}).transform((v) => {
    return remap$(v, {
        "finish_reason": "finishReason",
    });
});
export function completionChoiceFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CompletionChoice$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CompletionChoice' from JSON`);
}
//# sourceMappingURL=completionchoice.js.map