/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ResponsesFormatJSONObject$inboundSchema, ResponsesFormatJSONObject$outboundSchema, } from "./responsesformatjsonobject.js";
import { ResponsesFormatText$inboundSchema, ResponsesFormatText$outboundSchema, } from "./responsesformattext.js";
import { ResponsesFormatTextJSONSchemaConfig$inboundSchema, ResponsesFormatTextJSONSchemaConfig$outboundSchema, } from "./responsesformattextjsonschemaconfig.js";
/** @internal */
export const ResponseFormatTextConfig$inboundSchema = z.union([
    ResponsesFormatTextJSONSchemaConfig$inboundSchema,
    ResponsesFormatText$inboundSchema,
    ResponsesFormatJSONObject$inboundSchema,
]);
/** @internal */
export const ResponseFormatTextConfig$outboundSchema = z.union([
    ResponsesFormatTextJSONSchemaConfig$outboundSchema,
    ResponsesFormatText$outboundSchema,
    ResponsesFormatJSONObject$outboundSchema,
]);
export function responseFormatTextConfigToJSON(responseFormatTextConfig) {
    return JSON.stringify(ResponseFormatTextConfig$outboundSchema.parse(responseFormatTextConfig));
}
export function responseFormatTextConfigFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ResponseFormatTextConfig$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ResponseFormatTextConfig' from JSON`);
}
//# sourceMappingURL=responseformattextconfig.js.map