/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ChatMessageContentItemAudio$inboundSchema, ChatMessageContentItemAudio$outboundSchema, } from "./chatmessagecontentitemaudio.js";
import { ChatMessageContentItemFile$inboundSchema, ChatMessageContentItemFile$outboundSchema, } from "./chatmessagecontentitemfile.js";
import { ChatMessageContentItemImage$inboundSchema, ChatMessageContentItemImage$outboundSchema, } from "./chatmessagecontentitemimage.js";
import { ChatMessageContentItemText$inboundSchema, ChatMessageContentItemText$outboundSchema, } from "./chatmessagecontentitemtext.js";
import { ChatMessageContentItemVideo$inboundSchema, ChatMessageContentItemVideo$outboundSchema, } from "./chatmessagecontentitemvideo.js";
/** @internal */
export const ChatMessageContentItem$inboundSchema = z.union([
    ChatMessageContentItemText$inboundSchema.and(z.object({ type: z.literal("text") })),
    ChatMessageContentItemImage$inboundSchema.and(z.object({ type: z.literal("image_url") })),
    ChatMessageContentItemAudio$inboundSchema.and(z.object({ type: z.literal("input_audio") })),
    ChatMessageContentItemFile$inboundSchema.and(z.object({ type: z.literal("file") })),
    ChatMessageContentItemVideo$inboundSchema.and(z.object({ type: z.literal("input_video") })),
    z.lazy(() => ChatMessageContentItemVideo$inboundSchema).and(z.object({ type: z.literal("video_url") })),
]);
/** @internal */
export const ChatMessageContentItem$outboundSchema = z.union([
    ChatMessageContentItemText$outboundSchema.and(z.object({ type: z.literal("text") })),
    ChatMessageContentItemImage$outboundSchema.and(z.object({ type: z.literal("image_url") })),
    ChatMessageContentItemAudio$outboundSchema.and(z.object({ type: z.literal("input_audio") })),
    ChatMessageContentItemFile$outboundSchema.and(z.object({ type: z.literal("file") })),
    ChatMessageContentItemVideo$outboundSchema.and(z.object({ type: z.literal("input_video") })),
    z.lazy(() => ChatMessageContentItemVideo$outboundSchema).and(z.object({ type: z.literal("video_url") })),
]);
export function chatMessageContentItemToJSON(chatMessageContentItem) {
    return JSON.stringify(ChatMessageContentItem$outboundSchema.parse(chatMessageContentItem));
}
export function chatMessageContentItemFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ChatMessageContentItem$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ChatMessageContentItem' from JSON`);
}
//# sourceMappingURL=chatmessagecontentitem.js.map