/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { parametersGetParameters } from "../funcs/parametersGetParameters.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export class ParametersT extends ClientSDK {
    /**
     * Get a model's supported parameters and data about which are most popular
     */
    async getParameters(security, request, options) {
        return unwrapAsync(parametersGetParameters(this, security, request, options));
    }
}
//# sourceMappingURL=parameters.js.map