/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const GetCreditsResponse$inboundSchema = z.object({});
export function getCreditsResponseFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetCreditsResponse$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetCreditsResponse' from JSON`);
}
//# sourceMappingURL=getcredits.js.map