/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
/** @internal */
export const PublicPricing$inboundSchema = z
    .object({
    prompt: z.any().optional(),
    completion: z.any().optional(),
    request: z.any().optional(),
    image: z.any().optional(),
    image_token: z.any().optional(),
    image_output: z.any().optional(),
    audio: z.any().optional(),
    input_audio_cache: z.any().optional(),
    web_search: z.any().optional(),
    internal_reasoning: z.any().optional(),
    input_cache_read: z.any().optional(),
    input_cache_write: z.any().optional(),
    discount: z.number().optional(),
}).transform((v) => {
    return remap$(v, {
        "image_token": "imageToken",
        "image_output": "imageOutput",
        "input_audio_cache": "inputAudioCache",
        "web_search": "webSearch",
        "internal_reasoning": "internalReasoning",
        "input_cache_read": "inputCacheRead",
        "input_cache_write": "inputCacheWrite",
    });
});
export function publicPricingFromJSON(jsonString) {
    return safeParse(jsonString, (x) => PublicPricing$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'PublicPricing' from JSON`);
}
//# sourceMappingURL=publicpricing.js.map