/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod/v4";
/** @internal */
export const Security$outboundSchema = z
    .object({
    apiKey: z.string().optional(),
});
export function securityToJSON(security) {
    return JSON.stringify(Security$outboundSchema.parse(security));
}
//# sourceMappingURL=security.js.map